### ISSUE TITLE
PIP address configured for Kovan is not the same configured in SaiTub contract

### ISSUE THREAD

**Issue by lmcorbalan** [makerdao/dai.js#113]
The address configured in https://github.com/makerdao/dai.js/blob/dev/contracts/addresses/kovan.json#L4 is not the same address configured as **pip** in SaiTub contract deployed on Kovan (0xa5aA4e07F5255E14F02B385b1f04b35cC50bdb66)

So the ETH price obtained with `maker.service('price').getEthPrice()`  is not the same shown in https://cdp.makerdao.com/ under **Price Info** section

**Comment by levity** [comment]
Fixed in 023648d--thanks for the issue report!
