### ISSUE TITLE
can not use exchange service

### ISSUE THREAD

**Issue by davidinsuomi** [makerdao/dai.js#131]
I would like to use exchange service using the code below
```
await maker.authenticate()
const exchange = maker.service('exchange');

```
However, It throws errors directly. By the way, I did call maker.authenticate() before using maker.service('exchange'), Anyone could help me? Thanks a lot
```
error Error: Service with name 'exchange' cannot be found in this container.
    at new ServiceNotFoundError (node_modules/@makerdao/services-core/dist/Container.js:80:147)
    at Container.service (node_modules/@makerdao/services-core/dist/Container.js:165:15)
    at Maker.service (node_modules/@makerdao/dai/src/Maker.js:146:30)
```

**Comment by b-pmcg** [comment]
The exchange service was extracted from dai.js and into its own plugin. You can look at the readme here and see how to include it in your `maker` config:

https://github.com/makerdao/dai-plugin-eth2dai-direct

**Comment by ethanbennett** [comment]
And just to clarify, if you were using the default exchange service, this might actually be the plugin you want: https://github.com/makerdao/dai-plugin-maker-otc The one @b-pmcg linked has a lot more functionality; just pointing this plugin out in case it's the exchange service you were using before.
