### ISSUE TITLE
5000 requests on Infura by hour

### ISSUE THREAD

**Issue by ellis2323** [makerdao/dai.js#145]
I'm using dai.js with infura and i discover that i used my quota everyday (free account limited to 100k requests by day). After investigation, i removed this part and joy:

```
  gMakerTool = await Maker.create('http', {
    url: `https://mainnet.infura.io/v3/${config.infura.mainnet}`,
    web3: { statusTimerDelay: 15000 },
    log: false
  })
  await gMakerTool.authenticate()
  gCDPService = gMakerTool.service('cdp')
  gPriceService = gMakerTool.service('price')
```

Is it normal to use so many requests ?

Best regards

Edit: with the flag NODE_DEBUG=request, you can see all the requests.

It will show many requests like: eth_getBlockByNumber. The rate seems to be 1 per s! In this debug, it's like 4 four times the same query.
https://gist.github.com/ellis2323/85f2ee96fd83fe6144a96fff193bbdea

**Comment by levity** [comment]
Hmm, that seems very high. Thanks for the report; we'll look into it.

**Comment by ellis2323** [comment]
A little research and informations: i'm not using a Websocket. So `_listenForNewBlocks`

**Comment by ellis2323** [comment]
A debug session with node --inspect. The culprit is the 'eth-block-tracker' package. The polling rate is 4s... This package comes with 'web3-provider-engine'.

**Comment by ellis2323** [comment]
Ok, the solution is easy: define the variable pollingInterval in settings like:
```
  gMakerTool = await Maker.create('http', {
    url: `https://mainnet.infura.io/v3/${config.infura.mainnet}`,
    web3: { statusTimerDelay: 15000, pollingInterval: 15000 },
    log: true
  })
```
It overrides 3 timers which are setted by default at 2000, 3000 & 4000.

**Comment by levity** [comment]
Thanks for the research and the suggestion. We'll try to add this soon. Pull requests are welcome :)

**Comment by lvshaoping007** [comment]
const maker = await Maker.create('http', {
        privateKey:privateKey,
        url: `https://kovan.infura.io/v3/{id}`,
        web3: { statusTimerDelay: 15000, pollingInterval: 15000 },
        log: true
      })
    console.log('maker=00')
the console always show 
Web3 is initializing...
Web3 is connecting... 
why is this ?

**Comment by levity** [comment]
Hi @lvshaoping, please open a new issue instead of adding comments on other issues. Anyway, it looks like your `url` value is not valid. The `{id}` part should be a valid Infura API key.
