### ISSUE TITLE
Node 11.10 required ?

### ISSUE THREAD

**Issue by ellis2323** [makerdao/dai.js#151]
In packages/dai/package.json, at line 72, there's:
```
    "node": "11.10"
```
Not sure if this is the only version compatible. I'm using node 11.15 and it seems working
https://github.com/makerdao/dai.js/blob/dev/packages/dai/package.json

**Comment by mikewyszinski** [comment]
is this really only working on single version of node? seems overly restrictive

**Comment by ellis2323** [comment]
Not to use it, but to build the packages. I had to change that line in my case.

**Comment by ellis2323** [comment]
For yarn, it is an error. it will a good idea to fix this typo. thx

**Comment by mikewyszinski** [comment]
FWIW i bypassed this by running the install with the  ignore engines flag

``` 
yarn install --ignore-engines 
```
however we ended up removing dai.js from our dependencies because it added a lot of other deps and our use case was so simple we were able to acheivethe same with web3.js
