### ISSUE TITLE
How to build and get dai.js umd file?

### ISSUE THREAD

**Issue by djy0** [makerdao/dai.js#163]
I want to get a umd version of dai.js and use it like `<script src="./dai.js" />
`
But can't find a file I want after execute 
```
yarn
yarn lerna bootstrap
yarn build
```

**Comment by levity** [comment]
Hi! To do that, you can run:
```js
cd packages/dai
yarn build:frontend
```
and then you'll find a `main.[fingerprint].js` file in the `dist` folder. Please let us know if you run into any issues. I'll update our README with these instructions.

**Comment by djy0** [comment]
this helps, thanks
