### ISSUE TITLE
Unable to use in React Native - Get stuck at "Web3 is connecting..."

### ISSUE THREAD

**Issue by manuchandra962** [makerdao/dai.js#165]
<img width="1008" alt="Screen Shot 2019-09-27 at 6 07 05 PM" src="https://user-images.githubusercontent.com/5211176/65769638-a8141600-e151-11e9-8642-7f5ac6b77e25.png">
const maker = await Maker.create("http", {
      privateKey: PRIVATE_KEY,
      url: 'https://kovan.infura.io/v3/MY_PROJECT_ID'
    });

Works well with Ionic 4 and ReactJS

**Comment by manuchandra962** [comment]
<img width="1392" alt="Screen Shot 2019-09-27 at 6 36 17 PM" src="https://user-images.githubusercontent.com/5211176/65771410-bbc17b80-e155-11e9-8e68-a80783646243.png">

I tried to find where is going wrong, based on my analysis
this._web3.eth.getProtocolVersion().then(console.log)
Callbacks are returning/functioning.

**Comment by levity** [comment]
Hi @manuchandra962, I'm not sure we'll be able to offer much help, as React Native isn't one of our target platforms. If I were you, I would see if web3.js is known to have any issues with React Native, since we depend on that library heavily.

**Comment by lvshaoping007** [comment]
> Hi @manuchandra962, I'm not sure we'll be able to offer much help, as React Native isn't one of our target platforms. If I were you, I would see if web3.js is known to have any issues with React Native, since we depend on that library heavily.

i use node also have this program . 
it always shows 
Web3 is initializing...
Web3 is connecting... 
and i don`t konw how to use Maker.create  . there is not a docs to show this
