### ISSUE TITLE
mcd plugin

### ISSUE THREAD

**Issue by mostar93** [makerdao/dai.js#197]
when tryin to create an maker instance with the mcd plugin, i get an:

assertion error, message: Missing address for DGD on mainnet

**Comment by levity** [comment]
If you show me your code perhaps I can spot the issue.

**Comment by pcatana** [comment]
> when tryin to create an maker instance with the mcd plugin, i get an:
> 
> assertion error, message: Missing address for DGD on mainnet

Did you get the latest update of the plugin?
