### ISSUE TITLE
undefined is not an object (evaluating 'provider.sendPayload')

### ISSUE THREAD

**Issue by Ankarrr** [makerdao/dai.js#198]
Hi. When I use `@makerdao/dai`, it works fine. However, if I import `@makerdao/dai-plugin-mcd`, it shows this error:

<img width="351" alt="螢幕快照 2019-12-24 下午2 38 06" src="https://user-images.githubusercontent.com/8311552/71398336-0a01f000-265b-11ea-8ffc-cd85aa96d3ee.png">

I'm using:
@makerdao/dai 0.18.9
@makerdao/dai-plugin-mcd 1.0.5
node 10.17
also I'm using react native 0.59

**Comment by levity** [comment]
Hi @Ankarrr, sorry for the very delayed response. Did you find a solution to your issue?
