### ISSUE TITLE
yarn lerna bootstrap can not be run

### ISSUE THREAD

**Issue by saramirabi** [makerdao/dai.js#204]
Hi Guys,
I want to install dai.js on an ubuntu system, I run the relative query for Yarn and add the relative packages.
but now i faced with below error.
Anyone has an idea?

-------   yarn lerna bootstrap
yarn run v1.21.1
$ /home/sara/node_modules/.bin/lerna bootstrap
lerna notice cli v3.20.2
lerna ERR! ENOLERNA lerna.json does not exist, have you run lerna init?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by levity** [comment]
I see from your output that the `lerna` that is running is not where I would expect it to be, that is, under `node_modules` in the dai.js folder. Make sure you have run `yarn` from inside that folder.

**Comment by saramirabi** [comment]
You are completely correct Levity...This has been fixed, after creating dai.js i should write my command in that directory. Now i have a question for testchain?
How can i open a cdp how can i change the stability fee?
Is there any interface which i can see the commands which i apply?
