### ISSUE TITLE
@makerdao/dai-plugin-mcd 1.0.6 typescript issues

### ISSUE THREAD

**Issue by herman-rogers** [makerdao/dai.js#209]
Version 1.0.5 of the plugin works fine with my typescript setup but changes in version 1.0.6 have completely broken down with missing typescript definitions to 'BigNumber' and a host of other problems:

![Screen Shot 2020-02-17 at 11 51 52 AM](https://user-images.githubusercontent.com/3153479/74672831-1185d700-517c-11ea-9421-87319c1a6436.png)

Downgrading to 1.0.5 works but I'd like to support beyond this.

**Comment by michaelelliot** [comment]
This should now be fixed and available in `@makerdao/dai-plugin-mcd@1.3.1`.

Let me know if you're still having any issues.
