### ISSUE TITLE
how to use dai.js

### ISSUE THREAD

**Issue by yfhuang521** [makerdao/dai.js#237]
TypeError: maker.service is not a function

![image](https://user-images.githubusercontent.com/21332031/85124341-54f06f00-b25c-11ea-9d31-be910f7fedb0.png)

![image](https://user-images.githubusercontent.com/21332031/85124255-2ecacf00-b25c-11ea-979b-215379d859c2.png)

**Comment by levity** [comment]
Maker.create is an async function, so you need the `await` keyword:

```js
const maker = await Maker.create('http', {
```

You will need to wrap the sample code in an async function. I recommend reading a tutorial on async/await such as [this one](https://javascript.info/async-await). Check out the note on that page that says "await won’t work in the top-level code".
