### ISSUE TITLE
Metamask update not supported yet?

### ISSUE THREAD

**Issue by kraikov** [makerdao/dai.js#241]
After the latest Metamask update, the connection seems to be broken:

![image](https://user-images.githubusercontent.com/7030722/87538846-97636b00-c6a5-11ea-8ccb-7155dee5a0f7.png)

The way we create the maker instance is:

```
export const createMaker = async () => {
  return await Maker.create('browser', {
    plugins: [McdPlugin], // Add plugins, Mcd to support DAI (Multi collateral dai)
    multicall: true,
    web3: {
      pollingInterval: null,
    },
  });
};
```

Versions:

```
    "@makerdao/dai": "0.31.7",
    "@makerdao/dai-plugin-mcd": "1.5.12",
```

**Comment by levity** [comment]
Thanks for reporting this; I can reproduce it locally and am looking into it.

**Comment by levity** [comment]
This is a bug in the latest version of MetaMask: https://github.com/MetaMask/metamask-extension/pull/8998

I looked into where we're calling the broken method, though, and it's actually not necessary for startup. So I've removed the call and pushed version 0.32.0.
