### ISSUE TITLE
@makerdao/dai-plugin-mcd latest version doesn't work with typescript

### ISSUE THREAD

**Issue by viraj124** [makerdao/dai.js#249]
Hi,
I am trying to use the latest mcd plugin version on typescript, I am on Mac OS
Node Version -> v12.6.0
NPM version -> 6.9.0

When I do npm install with the latest version 1.5.17 I get the following error:
File node_modules/@makerdao/dai-plugin-mcd/typings/index.d.ts' is not a module.

I am importing like this => import McdPlugin from '@makerdao/dai-plugin-mcd';

Please look into or let me know how can I help?

**Comment by levity** [comment]
Hi @viraj124, please try upgrading to version `1.6.0-rc` and let us know if this solves your issue.

**Comment by viraj124** [comment]
Sure

**Comment by viraj124** [comment]
Hey @levity I don't get the error now though this =>   const maker = await Maker.create('http', {
            url: env.alchemy.http + env.alchemy.stageKey,
            plugins: [[McdPlugin]],
        });
get's timed out now.
these are the versions I am using
 "@makerdao/dai": "0.32.2",
 "@makerdao/dai-plugin-mcd": "1.6.0-rc",

**Comment by levity** [comment]
if you use the value `'https://mainnet.infura.io/v3/7d0d81d0919f4f05b9ab6634be01ee73'` for `url`, do you still get a timeout?

**Comment by viraj124** [comment]
I will try this and keep you posted

**Comment by viraj124** [comment]
Yes it works @levity  :)
Will close it now

**Comment by viraj124** [comment]
Resolved
