### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by varon-bardus** [makerdao/dai.js#31]
![image](https://user-images.githubusercontent.com/33404666/43973381-c2a1d88e-9cad-11e8-986c-11031f35a8c4.png)

I'm getting this error just trying the readme example.

**Comment by levity** [comment]
Hi @varon-bardus, you'll want to add `babel-polyfill` to the Webpack setup of your app. See this StackOverflow answer for details: https://stackoverflow.com/a/33527883/56817

**Comment by levity** [comment]
I just pushed a new version (0.5.7) that should remove the need to add `babel-polyfill`. Please let me know if it works for you.

**Comment by varon-bardus** [comment]
It works!

Thank you.
