### ISSUE TITLE
Unhandled Rejection (Error): Cannot resolve network ID. Are you connected?

### ISSUE THREAD

**Issue by varon-bardus** [makerdao/dai.js#33]
I'm trying to get the Eth price with:
```
const price = maker.service('price');
const ethPrice = await price.getEthPrice();
```

![image](https://user-images.githubusercontent.com/33404666/44112858-ae062704-9fdc-11e8-80d1-11a27f0ee7e2.png)

Any idea?

**Comment by ethanbennett** [comment]
@varon-bardus Can you paste your config and/or `Maker.create(...)` here? It looks like it's trying to connect to a network with ID 5777 here, which isn't a valid network ID.

**Comment by varon-bardus** [comment]
I'm using "test" network, with Ganache running on http://127.0.0.1:2000 as documentation stays. Ganache's default network id is 5777, should I use another one? I thought that was find as docs doesn't specifies it.
Thank you.

**Comment by ethanbennett** [comment]
Oh, I see. We should add that to the docs. Are you running our script to deploy all the Maker contracts on Ganache? If not, you can do that by cloning the repo and running `./testchain/scripts/with-deployed-system` from the root directory. This will set you up with a Ganache environment that has all our contracts deployed, price feeds configured, etc.

If you're already doing that and still hitting this error, try changing the network ID to `999`.
