### ISSUE TITLE
dai SVG icon

### ISSUE THREAD

**Issue by mesqueeb** [makerdao/dai.js#57]
Any SVG icons available for DAI?

**Comment by mikedemarais** [comment]
@mesqueeb check out https://github.com/atomiclabs/cryptocurrency-icons and https://github.com/balance-io/react-coin-icon

**Comment by gitdk** [comment]
@mesqueeb you can use these as well. 
[dai svg.zip](https://github.com/makerdao/dai.js/files/2494587/dai.svg.zip)
