### ISSUE TITLE
Add support for xDAI side chain

### ISSUE THREAD

**Issue by andersonmmi** [makerdao/dai.js#65]
dai.js does not seem to know the address of the xDAI sidechain contract.

While building a hackathon project we tried to use the switch statement to access the xDAI sidechain, but it did not connect.  We were accessessing our dApp through the Status mobile browser.

**Comment by ethanbennett** [comment]
Thanks for filing this issue, @andersonmmi . xDai was a bit of a pleasant surprise for us, so we hadn't yet considered what kind of integration with the SDK would be helpful. We'll try to get something added soon! In the mean time, if you have any other feedback about working with the library, we'd love to hear it. Feel free to reach out on rocket chat too (chat.makerdao.com)
