### ISSUE TITLE
ethereumjs-util not specified in dependencies

### ISSUE THREAD

**Issue by graemecode** [makerdao/dai.js#83]
I might not be assessing this correctly, but I see `require('ethereumjs-util')` in `src/eth/accounts/factories.js`, but ethereumjs-util is not specified in the package dependencies. Our app is resolving to a different version of ethereumjs-util that we have installed.

**Comment by levity** [comment]
It's a dependency of `web3-provider-engine`, so it's available once dependencies are installed. But you make a good point; it should be listed in package.json since it's being required directly.
